---

language: python
python: "2.7"

#before_install:
  #making sure if everything is up to date


script:
  - ansible-playbook servera playbook.yml --connection=local
  - "ansible-playbook servera playbook.yml | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)"
  - curl http://localhost/
