---

# tasks file for dipesh.myenv

- name: cheack myenv_user default
  fail: 
    msg: You must specify the variable 'myenv-user' to use this role!
  when: "myenv_user == ''"

- name: install my packages
  yum: 
    name: "{{ item }}"
    state: installed
  with_items: "{{ myenv_packages }}"

- name: set an alias in bashrc
  lineinfile:
    line: "alias tree='tree -C'"
    dest: "~{{myenv_user}}/.bashrc"

